#include "engine.h"

struct csApi
{
	int p_csCoreInit;
	int p_csCoreFinish;
	int p_csCoreMessage;
	int p_csBillboardNode;
	int p_csBillboardResize;
	int p_csBillboardWidth;
	int p_csBillboardHeight;
	int p_csCameraNode;
	int p_csCameraViewport;
	int p_csCameraRange;
	int p_csCameraFov;
	int p_csCameraAspectRatio;
	int p_csCameraProjection;
	int p_csCameraLine;
	int p_csCameraPickNode;
	int p_csCameraToScreen;
	int p_csCameraRenderTarget;
	int p_csCollisionSlide;
	int p_csCollisionLinePick;
	int p_csCollisionLineNode;
	int p_csPackageAdd;
	int p_csDirList;
	int p_csDirClose;
	int p_csDirFileCount;
	int p_csDirFileName;
	int p_csDirFileIsDir;
	int p_csDisplayOpen;
	int p_csDisplayClose;
	int p_csDisplayCaption;
	int p_csDisplayClosed;
	int p_csDisplayWidth;
	int p_csDisplayHeight;
	int p_csDisplayFps;
	int p_csDisplayFeature;
	int p_csDisplayResize;
	int p_csDisplayActive;
	int p_csGetColor;
	int p_csGetRed;
	int p_csGetGreen;
	int p_csGetBlue;
	int p_csGetAlpha;
	int p_csSetColor;
	int p_csViewport;
	int p_csDrawLine;
	int p_csDrawRect;
	int p_csDrawTexture;
	int p_csDrawText;
	int p_csTextWidth;
	int p_csTextHeight;
	int p_csEffectRegister;
	int p_csEffectRegisterFile;
	int p_csEffectSetTechnique;
	int p_csEffectSetTexture;
	int p_csEffectSetBool;
	int p_csEffectSetInt;
	int p_csEffectSetFloat;
	int p_csEffectSetVector;
	int p_csEffectSetMatrix;
	int p_csEmitterNode;
	int p_csEmitterAddFadeOutAffector;
	int p_csEmitterAddGravityAffector;
	int p_csEmitterRemoveAffectors;
	int p_csEventGet;
	int p_csEventPoll;
	int p_csEventPost;
	int p_csEventId;
	int p_csEventFrom;
	int p_csEventTo;
	int p_csEventA;
	int p_csEventB;
	int p_csEventC;
	int p_csEventData;
	int p_csFileRead;
	int p_csFileWrite;
	int p_csFileClose;
	int p_csFileSize;
	int p_csFilePos;
	int p_csFileSeek;
	int p_csFileReadByte;
	int p_csFileReadShort;
	int p_csFileReadInt;
	int p_csFileReadFloat;
	int p_csFileReadString;
	int p_csFileReadBytes;
	int p_csFileWriteByte;
	int p_csFileWriteShort;
	int p_csFileWriteInt;
	int p_csFileWriteFloat;
	int p_csFileWriteString;
	int p_csFileWriteBytes;
	int p_csFileGetExt;
	int p_csFileGetDir;
	int p_csFileStripExt;
	int p_csFileStripDir;
	int p_csFontLoad;
	int p_csFontFree;
	int p_csMousePosition;
	int p_csMouseHide;
	int p_csMouseX;
	int p_csMouseY;
	int p_csMouseHit;
	int p_csMouseDown;
	int p_csMouseGet;
	int p_csMouseReleased;
	int p_csKeyHit;
	int p_csKeyDown;
	int p_csKeyGet;
	int p_csKeyReleased;
	int p_csJoyName;
	int p_csJoyButton;
	int p_csJoyAxis;
	int p_csJoyNumAxes;
	int p_csLightNode;
	int p_csLightType;
	int p_csLightRadius;
	int p_csLightAmbient;
	int p_csLightDiffuse;
	int p_csLightSpecular;
	int p_csMaterialCreate;
	int p_csMaterialLoad;
	int p_csMaterialSave;
	int p_csMaterialFree;
	int p_csMaterialFind;
	int p_csMaterialSetType;
	int p_csMaterialSetFlags;
	int p_csMaterialSetTexture;
	int p_csMaterialSetAmbient;
	int p_csMaterialSetDiffuse;
	int p_csMaterialSetEmissive;
	int p_csMaterialSetSpecular;
	int p_csMaterialSetShininess;
	int p_csMaterialSetParam;
	int p_csMaterialGetName;
	int p_csMaterialGetType;
	int p_csMaterialGetFlags;
	int p_csMaterialGetTexture;
	int p_csMaterialGetAmbient;
	int p_csMaterialGetDiffuse;
	int p_csMaterialGetEmissive;
	int p_csMaterialGetSpecular;
	int p_csMaterialGetShininess;
	int p_csMaterialGetParam;
	int p_csMathFloor;
	int p_csMathCeil;
	int p_csMathAbs;
	int p_csMathSqr;
	int p_csMathSin;
	int p_csMathCos;
	int p_csMathTan;
	int p_csMathASin;
	int p_csMathACos;
	int p_csMathATan;
	int p_csMathATan2;
	int p_csMathExp;
	int p_csMathLog;
	int p_csMathLog10;
	int p_csMathRand;
	int p_csMathRandSeed;
	int p_csMatrixCreate;
	int p_csMatrixFree;
	int p_csMatrixAdd;
	int p_csMatrixCopy;
	int p_csMatrixDiv;
	int p_csMatrixElement;
	int p_csMatrixEqual;
	int p_csMatrixGetRotation;
	int p_csMatrixGetTranslation;
	int p_csMatrixIdentity;
	int p_csMatrixInterpolate;
	int p_csMatrixInvert;
	int p_csMatrixMul;
	int p_csMatrixSet;
	int p_csMatrixSetRotation;
	int p_csMatrixSetScale;
	int p_csMatrixSetTranslation;
	int p_csMatrixSub;
	int p_csMatrixTranspose;
	int p_csMeshLoad;
	int p_csMeshTerrainLoad;
	int p_csMeshFree;
	int p_csMeshNode;
	int p_csMeshOctreeNode;
	int p_csMeshScale;
	int p_csMeshFlip;
	int p_csMeshUpdateNormals;
	int p_csMeshVerticesColor;
	int p_csMeshPlanarMapping;
	int p_csMeshWidth;
	int p_csMeshHeight;
	int p_csMeshDepth;
	int p_csNodeEmpty;
	int p_csNodeFree;
	int p_csNodeType;
	int p_csNodeSetName;
	int p_csNodeGetName;
	int p_csNodePosition;
	int p_csNodeMove;
	int p_csNodeRotate;
	int p_csNodeTurn;
	int p_csNodeScale;
	int p_csNodeX;
	int p_csNodeY;
	int p_csNodeZ;
	int p_csNodePitch;
	int p_csNodeYaw;
	int p_csNodeRoll;
	int p_csNodeScaleX;
	int p_csNodeScaleY;
	int p_csNodeScaleZ;
	int p_csNodeWidth;
	int p_csNodeHeight;
	int p_csNodeDepth;
	int p_csNodeCastShadow;
	int p_csNodeHide;
	int p_csNodeMaterials;
	int p_csNodeGetMaterial;
	int p_csNodeSetMaterial;
	int p_csNodeSetMaterialFast;
	int p_csNodeSetMaterialFlag;
	int p_csNodeSetPickGroup;
	int p_csNodeSetProperty;
	int p_csNodeProperties;
	int p_csNodeFindProperty;
	int p_csNodePropertyName;
	int p_csNodePropertyValue;
	int p_csNodeRemoveProperty;
	int p_csNodeSetParent;
	int p_csNodeGetParent;
	int p_csNodeChildren;
	int p_csNodeChild;
	int p_csNodeFindChild;
	int p_csNodeSpeed;
	int p_csNodeLoop;
	int p_csNodeSetFrame;
	int p_csNodeGetFrame;
	int p_csNodeAttachToBone;
	int p_csNodeLookAt;
	int p_csParticleDataCreate;
	int p_csParticleDataLoad;
	int p_csParticleDataSave;
	int p_csParticleDataFree;
	int p_csParticleDataFind;
	int p_csParticleDataSetMaterial;
	int p_csParticleDataSetType;
	int p_csParticleDataSetBox;
	int p_csParticleDataSetDirection;
	int p_csParticleDataSetRate;
	int p_csParticleDataSetColor;
	int p_csParticleDataSetLifeTime;
	int p_csParticleDataSetMaxAngle;
	int p_csParticleDataSetSize;
	int p_csParticleDataAddFadeOutAffector;
	int p_csParticleDataAddGravityAffector;
	int p_csParticleDataGetName;
	int p_csParticleDataGetMaterial;
	int p_csParticleDataGetType;
	int p_csParticleDataGetBoxWidth;
	int p_csParticleDataGetBoxHeight;
	int p_csParticleDataGetBoxDepth;
	int p_csParticleDataGetDirectionX;
	int p_csParticleDataGetDirectionY;
	int p_csParticleDataGetDirectionZ;
	int p_csParticleDataGetMinRate;
	int p_csParticleDataGetMaxRate;
	int p_csParticleDataGetMinColor;
	int p_csParticleDataGetMaxColor;
	int p_csParticleDataGetMinLifeTime;
	int p_csParticleDataGetMaxLifeTime;
	int p_csParticleDataGetMaxAngle;
	int p_csParticleDataGetWidth;
	int p_csParticleDataGetHeight;
	int p_csParticleDataAffectors;
	int p_csParticleDataGetAffectorType;
	int p_csParticleDataGetAffectorColor;
	int p_csParticleDataGetAffectorTime;
	int p_csParticleDataGetAffectorGravityX;
	int p_csParticleDataGetAffectorGravityY;
	int p_csParticleDataGetAffectorGravityZ;
	int p_csSceneBegin;
	int p_csSceneEnd;
	int p_csSceneRender;
	int p_csSceneAmbient;
	int p_csSceneFog;
	int p_csSceneSkybox;
	int p_csSceneTransformation;
	int p_csShaderRegister;
	int p_csShaderRegisterFile;
	int p_csShaderAsmRegister;
	int p_csShaderAsmRegisterFile;
	int p_csShaderPixelConstant;
	int p_csShaderVertexConstant;
	int p_csStringToInt;
	int p_csStringToFloat;
	int p_csStringFromInt;
	int p_csStringFromFloat;
	int p_csStringLeft;
	int p_csStringRight;
	int p_csStringMid;
	int p_csStringReplace;
	int p_csStringFind;
	int p_csStringUpper;
	int p_csStringLower;
	int p_csStringTrim;
	int p_csStringChar;
	int p_csStringAscii;
	int p_csStringLen;
	int p_csStringField;
	int p_csTerrainNode;
	int p_csTerrainScaleTexture;
	int p_csTextureCreate;
	int p_csTextureTargetCreate;
	int p_csTextureLoad;
	int p_csTextureFree;
	int p_csTextureFile;
	int p_csTextureWidth;
	int p_csTextureHeight;
	int p_csTextureLock;
	int p_csTextureUnlock;
	int p_csTextureColorKey;
	int p_csTextureNormalize;
	int p_csTextureHWPointer;
	int p_csVectorCreate;
	int p_csVectorFree;
	int p_csVectorAdd;
	int p_csVectorAddScale;
	int p_csVectorBetween;
	int p_csVectorCopy;
	int p_csVectorCrossProduct;
	int p_csVectorDotProduct;
	int p_csVectorEqual;
	int p_csVectorDistance;
	int p_csVectorDistanceSquared;
	int p_csVectorDiv;
	int p_csVectorInterpolate;
	int p_csVectorInvert;
	int p_csVectorLength;
	int p_csVectorLengthSquared;
	int p_csVectorMul;
	int p_csVectorNormalize;
	int p_csVectorScale;
	int p_csVectorSet;
	int p_csVectorSub;
	int p_csVectorX;
	int p_csVectorY;
	int p_csVectorZ;
	int p_csXMLRead;
	int p_csXMLWrite;
	int p_csXMLClose;
	int p_csXMLReadNode;
	int p_csXMLNodeType;
	int p_csXMLNodeName;
	int p_csXMLNodeData;
	int p_csXMLAttributeCount;
	int p_csXMLAttributeName;
	int p_csXMLAttributeValue;
	int p_csXMLWriteHeader;
	int p_csXMLWriteElement;
	int p_csXMLWriteClosingTag;
	int p_csXMLWriteText;
	int p_csXMLWriteLineBreak;
} Api;

int ExportApi()
{
	Api.p_csCoreInit = (int) csCoreInit;
	Api.p_csCoreFinish = (int) csCoreFinish;
	Api.p_csCoreMessage = (int) csCoreMessage;
	Api.p_csBillboardNode = (int) csBillboardNode;
	Api.p_csBillboardResize = (int) csBillboardResize;
	Api.p_csBillboardWidth = (int) csBillboardWidth;
	Api.p_csBillboardHeight = (int) csBillboardHeight;
	Api.p_csCameraNode = (int) csCameraNode;
	Api.p_csCameraViewport = (int) csCameraViewport;
	Api.p_csCameraRange = (int) csCameraRange;
	Api.p_csCameraFov = (int) csCameraFov;
	Api.p_csCameraAspectRatio = (int) csCameraAspectRatio;
	Api.p_csCameraProjection = (int) csCameraProjection;
	Api.p_csCameraLine = (int) csCameraLine;
	Api.p_csCameraPickNode = (int) csCameraPickNode;
	Api.p_csCameraToScreen = (int) csCameraToScreen;
	Api.p_csCameraRenderTarget = (int) csCameraRenderTarget;
	Api.p_csCollisionSlide = (int) csCollisionSlide;
	Api.p_csCollisionLinePick = (int) csCollisionLinePick;
	Api.p_csCollisionLineNode = (int) csCollisionLineNode;
	Api.p_csPackageAdd = (int) csPackageAdd;
	Api.p_csDirList = (int) csDirList;
	Api.p_csDirClose = (int) csDirClose;
	Api.p_csDirFileCount = (int) csDirFileCount;
	Api.p_csDirFileName = (int) csDirFileName;
	Api.p_csDirFileIsDir = (int) csDirFileIsDir;
	Api.p_csDisplayOpen = (int) csDisplayOpen;
	Api.p_csDisplayClose = (int) csDisplayClose;
	Api.p_csDisplayCaption = (int) csDisplayCaption;
	Api.p_csDisplayClosed = (int) csDisplayClosed;
	Api.p_csDisplayWidth = (int) csDisplayWidth;
	Api.p_csDisplayHeight = (int) csDisplayHeight;
	Api.p_csDisplayFps = (int) csDisplayFps;
	Api.p_csDisplayFeature = (int) csDisplayFeature;
	Api.p_csDisplayResize = (int) csDisplayResize;
	Api.p_csDisplayActive = (int) csDisplayActive;
	Api.p_csGetColor = (int) csGetColor;
	Api.p_csGetRed = (int) csGetRed;
	Api.p_csGetGreen = (int) csGetGreen;
	Api.p_csGetBlue = (int) csGetBlue;
	Api.p_csGetAlpha = (int) csGetAlpha;
	Api.p_csSetColor = (int) csSetColor;
	Api.p_csViewport = (int) csViewport;
	Api.p_csDrawLine = (int) csDrawLine;
	Api.p_csDrawRect = (int) csDrawRect;
	Api.p_csDrawTexture = (int) csDrawTexture;
	Api.p_csDrawText = (int) csDrawText;
	Api.p_csTextWidth = (int) csTextWidth;
	Api.p_csTextHeight = (int) csTextHeight;
	Api.p_csEffectRegister = (int) csEffectRegister;
	Api.p_csEffectRegisterFile = (int) csEffectRegisterFile;
	Api.p_csEffectSetTechnique = (int) csEffectSetTechnique;
	Api.p_csEffectSetTexture = (int) csEffectSetTexture;
	Api.p_csEffectSetBool = (int) csEffectSetBool;
	Api.p_csEffectSetInt = (int) csEffectSetInt;
	Api.p_csEffectSetFloat = (int) csEffectSetFloat;
	Api.p_csEffectSetVector = (int) csEffectSetVector;
	Api.p_csEffectSetMatrix = (int) csEffectSetMatrix;
	Api.p_csEmitterNode = (int) csEmitterNode;
	Api.p_csEmitterAddFadeOutAffector = (int) csEmitterAddFadeOutAffector;
	Api.p_csEmitterAddGravityAffector = (int) csEmitterAddGravityAffector;
	Api.p_csEmitterRemoveAffectors = (int) csEmitterRemoveAffectors;
	Api.p_csEventGet = (int) csEventGet;
	Api.p_csEventPoll = (int) csEventPoll;
	Api.p_csEventPost = (int) csEventPost;
	Api.p_csEventId = (int) csEventId;
	Api.p_csEventFrom = (int) csEventFrom;
	Api.p_csEventTo = (int) csEventTo;
	Api.p_csEventA = (int) csEventA;
	Api.p_csEventB = (int) csEventB;
	Api.p_csEventC = (int) csEventC;
	Api.p_csEventData = (int) csEventData;
	Api.p_csFileRead = (int) csFileRead;
	Api.p_csFileWrite = (int) csFileWrite;
	Api.p_csFileClose = (int) csFileClose;
	Api.p_csFileSize = (int) csFileSize;
	Api.p_csFilePos = (int) csFilePos;
	Api.p_csFileSeek = (int) csFileSeek;
	Api.p_csFileReadByte = (int) csFileReadByte;
	Api.p_csFileReadShort = (int) csFileReadShort;
	Api.p_csFileReadInt = (int) csFileReadInt;
	Api.p_csFileReadFloat = (int) csFileReadFloat;
	Api.p_csFileReadString = (int) csFileReadString;
	Api.p_csFileReadBytes = (int) csFileReadBytes;
	Api.p_csFileWriteByte = (int) csFileWriteByte;
	Api.p_csFileWriteShort = (int) csFileWriteShort;
	Api.p_csFileWriteInt = (int) csFileWriteInt;
	Api.p_csFileWriteFloat = (int) csFileWriteFloat;
	Api.p_csFileWriteString = (int) csFileWriteString;
	Api.p_csFileWriteBytes = (int) csFileWriteBytes;
	Api.p_csFileGetExt = (int) csFileGetExt;
	Api.p_csFileGetDir = (int) csFileGetDir;
	Api.p_csFileStripExt = (int) csFileStripExt;
	Api.p_csFileStripDir = (int) csFileStripDir;
	Api.p_csFontLoad = (int) csFontLoad;
	Api.p_csFontFree = (int) csFontFree;
	Api.p_csMousePosition = (int) csMousePosition;
	Api.p_csMouseHide = (int) csMouseHide;
	Api.p_csMouseX = (int) csMouseX;
	Api.p_csMouseY = (int) csMouseY;
	Api.p_csMouseHit = (int) csMouseHit;
	Api.p_csMouseDown = (int) csMouseDown;
	Api.p_csMouseGet = (int) csMouseGet;
	Api.p_csMouseReleased = (int) csMouseReleased;
	Api.p_csKeyHit = (int) csKeyHit;
	Api.p_csKeyDown = (int) csKeyDown;
	Api.p_csKeyGet = (int) csKeyGet;
	Api.p_csKeyReleased = (int) csKeyReleased;
	Api.p_csJoyName = (int) csJoyName;
	Api.p_csJoyButton = (int) csJoyButton;
	Api.p_csJoyAxis = (int) csJoyAxis;
	Api.p_csJoyNumAxes = (int) csJoyNumAxes;
	Api.p_csLightNode = (int) csLightNode;
	Api.p_csLightType = (int) csLightType;
	Api.p_csLightRadius = (int) csLightRadius;
	Api.p_csLightAmbient = (int) csLightAmbient;
	Api.p_csLightDiffuse = (int) csLightDiffuse;
	Api.p_csLightSpecular = (int) csLightSpecular;
	Api.p_csMaterialCreate = (int) csMaterialCreate;
	Api.p_csMaterialLoad = (int) csMaterialLoad;
	Api.p_csMaterialSave = (int) csMaterialSave;
	Api.p_csMaterialFree = (int) csMaterialFree;
	Api.p_csMaterialFind = (int) csMaterialFind;
	Api.p_csMaterialSetType = (int) csMaterialSetType;
	Api.p_csMaterialSetFlags = (int) csMaterialSetFlags;
	Api.p_csMaterialSetTexture = (int) csMaterialSetTexture;
	Api.p_csMaterialSetAmbient = (int) csMaterialSetAmbient;
	Api.p_csMaterialSetDiffuse = (int) csMaterialSetDiffuse;
	Api.p_csMaterialSetEmissive = (int) csMaterialSetEmissive;
	Api.p_csMaterialSetSpecular = (int) csMaterialSetSpecular;
	Api.p_csMaterialSetShininess = (int) csMaterialSetShininess;
	Api.p_csMaterialSetParam = (int) csMaterialSetParam;
	Api.p_csMaterialGetName = (int) csMaterialGetName;
	Api.p_csMaterialGetType = (int) csMaterialGetType;
	Api.p_csMaterialGetFlags = (int) csMaterialGetFlags;
	Api.p_csMaterialGetTexture = (int) csMaterialGetTexture;
	Api.p_csMaterialGetAmbient = (int) csMaterialGetAmbient;
	Api.p_csMaterialGetDiffuse = (int) csMaterialGetDiffuse;
	Api.p_csMaterialGetEmissive = (int) csMaterialGetEmissive;
	Api.p_csMaterialGetSpecular = (int) csMaterialGetSpecular;
	Api.p_csMaterialGetShininess = (int) csMaterialGetShininess;
	Api.p_csMaterialGetParam = (int) csMaterialGetParam;
	Api.p_csMathFloor = (int) csMathFloor;
	Api.p_csMathCeil = (int) csMathCeil;
	Api.p_csMathAbs = (int) csMathAbs;
	Api.p_csMathSqr = (int) csMathSqr;
	Api.p_csMathSin = (int) csMathSin;
	Api.p_csMathCos = (int) csMathCos;
	Api.p_csMathTan = (int) csMathTan;
	Api.p_csMathASin = (int) csMathASin;
	Api.p_csMathACos = (int) csMathACos;
	Api.p_csMathATan = (int) csMathATan;
	Api.p_csMathATan2 = (int) csMathATan2;
	Api.p_csMathExp = (int) csMathExp;
	Api.p_csMathLog = (int) csMathLog;
	Api.p_csMathLog10 = (int) csMathLog10;
	Api.p_csMathRand = (int) csMathRand;
	Api.p_csMathRandSeed = (int) csMathRandSeed;
	Api.p_csMatrixCreate = (int) csMatrixCreate;
	Api.p_csMatrixFree = (int) csMatrixFree;
	Api.p_csMatrixAdd = (int) csMatrixAdd;
	Api.p_csMatrixCopy = (int) csMatrixCopy;
	Api.p_csMatrixDiv = (int) csMatrixDiv;
	Api.p_csMatrixElement = (int) csMatrixElement;
	Api.p_csMatrixEqual = (int) csMatrixEqual;
	Api.p_csMatrixGetRotation = (int) csMatrixGetRotation;
	Api.p_csMatrixGetTranslation = (int) csMatrixGetTranslation;
	Api.p_csMatrixIdentity = (int) csMatrixIdentity;
	Api.p_csMatrixInterpolate = (int) csMatrixInterpolate;
	Api.p_csMatrixInvert = (int) csMatrixInvert;
	Api.p_csMatrixMul = (int) csMatrixMul;
	Api.p_csMatrixSet = (int) csMatrixSet;
	Api.p_csMatrixSetRotation = (int) csMatrixSetRotation;
	Api.p_csMatrixSetScale = (int) csMatrixSetScale;
	Api.p_csMatrixSetTranslation = (int) csMatrixSetTranslation;
	Api.p_csMatrixSub = (int) csMatrixSub;
	Api.p_csMatrixTranspose = (int) csMatrixTranspose;
	Api.p_csMeshLoad = (int) csMeshLoad;
	Api.p_csMeshTerrainLoad = (int) csMeshTerrainLoad;
	Api.p_csMeshFree = (int) csMeshFree;
	Api.p_csMeshNode = (int) csMeshNode;
	Api.p_csMeshOctreeNode = (int) csMeshOctreeNode;
	Api.p_csMeshScale = (int) csMeshScale;
	Api.p_csMeshFlip = (int) csMeshFlip;
	Api.p_csMeshUpdateNormals = (int) csMeshUpdateNormals;
	Api.p_csMeshVerticesColor = (int) csMeshVerticesColor;
	Api.p_csMeshPlanarMapping = (int) csMeshPlanarMapping;
	Api.p_csMeshWidth = (int) csMeshWidth;
	Api.p_csMeshHeight = (int) csMeshHeight;
	Api.p_csMeshDepth = (int) csMeshDepth;
	Api.p_csNodeEmpty = (int) csNodeEmpty;
	Api.p_csNodeFree = (int) csNodeFree;
	Api.p_csNodeType = (int) csNodeType;
	Api.p_csNodeSetName = (int) csNodeSetName;
	Api.p_csNodeGetName = (int) csNodeGetName;
	Api.p_csNodePosition = (int) csNodePosition;
	Api.p_csNodeMove = (int) csNodeMove;
	Api.p_csNodeRotate = (int) csNodeRotate;
	Api.p_csNodeTurn = (int) csNodeTurn;
	Api.p_csNodeScale = (int) csNodeScale;
	Api.p_csNodeX = (int) csNodeX;
	Api.p_csNodeY = (int) csNodeY;
	Api.p_csNodeZ = (int) csNodeZ;
	Api.p_csNodePitch = (int) csNodePitch;
	Api.p_csNodeYaw = (int) csNodeYaw;
	Api.p_csNodeRoll = (int) csNodeRoll;
	Api.p_csNodeScaleX = (int) csNodeScaleX;
	Api.p_csNodeScaleY = (int) csNodeScaleY;
	Api.p_csNodeScaleZ = (int) csNodeScaleZ;
	Api.p_csNodeWidth = (int) csNodeWidth;
	Api.p_csNodeHeight = (int) csNodeHeight;
	Api.p_csNodeDepth = (int) csNodeDepth;
	Api.p_csNodeCastShadow = (int) csNodeCastShadow;
	Api.p_csNodeHide = (int) csNodeHide;
	Api.p_csNodeMaterials = (int) csNodeMaterials;
	Api.p_csNodeGetMaterial = (int) csNodeGetMaterial;
	Api.p_csNodeSetMaterial = (int) csNodeSetMaterial;
	Api.p_csNodeSetMaterialFast = (int) csNodeSetMaterialFast;
	Api.p_csNodeSetMaterialFlag = (int) csNodeSetMaterialFlag;
	Api.p_csNodeSetPickGroup = (int) csNodeSetPickGroup;
	Api.p_csNodeSetProperty = (int) csNodeSetProperty;
	Api.p_csNodeProperties = (int) csNodeProperties;
	Api.p_csNodeFindProperty = (int) csNodeFindProperty;
	Api.p_csNodePropertyName = (int) csNodePropertyName;
	Api.p_csNodePropertyValue = (int) csNodePropertyValue;
	Api.p_csNodeRemoveProperty = (int) csNodeRemoveProperty;
	Api.p_csNodeSetParent = (int) csNodeSetParent;
	Api.p_csNodeGetParent = (int) csNodeGetParent;
	Api.p_csNodeChildren = (int) csNodeChildren;
	Api.p_csNodeChild = (int) csNodeChild;
	Api.p_csNodeFindChild = (int) csNodeFindChild;
	Api.p_csNodeSpeed = (int) csNodeSpeed;
	Api.p_csNodeLoop = (int) csNodeLoop;
	Api.p_csNodeSetFrame = (int) csNodeSetFrame;
	Api.p_csNodeGetFrame = (int) csNodeGetFrame;
	Api.p_csNodeAttachToBone = (int) csNodeAttachToBone;
	Api.p_csNodeLookAt = (int) csNodeLookAt;
	Api.p_csParticleDataCreate = (int) csParticleDataCreate;
	Api.p_csParticleDataLoad = (int) csParticleDataLoad;
	Api.p_csParticleDataSave = (int) csParticleDataSave;
	Api.p_csParticleDataFree = (int) csParticleDataFree;
	Api.p_csParticleDataFind = (int) csParticleDataFind;
	Api.p_csParticleDataSetMaterial = (int) csParticleDataSetMaterial;
	Api.p_csParticleDataSetType = (int) csParticleDataSetType;
	Api.p_csParticleDataSetBox = (int) csParticleDataSetBox;
	Api.p_csParticleDataSetDirection = (int) csParticleDataSetDirection;
	Api.p_csParticleDataSetRate = (int) csParticleDataSetRate;
	Api.p_csParticleDataSetColor = (int) csParticleDataSetColor;
	Api.p_csParticleDataSetLifeTime = (int) csParticleDataSetLifeTime;
	Api.p_csParticleDataSetMaxAngle = (int) csParticleDataSetMaxAngle;
	Api.p_csParticleDataSetSize = (int) csParticleDataSetSize;
	Api.p_csParticleDataAddFadeOutAffector = (int) csParticleDataAddFadeOutAffector;
	Api.p_csParticleDataAddGravityAffector = (int) csParticleDataAddGravityAffector;
	Api.p_csParticleDataGetName = (int) csParticleDataGetName;
	Api.p_csParticleDataGetMaterial = (int) csParticleDataGetMaterial;
	Api.p_csParticleDataGetType = (int) csParticleDataGetType;
	Api.p_csParticleDataGetBoxWidth = (int) csParticleDataGetBoxWidth;
	Api.p_csParticleDataGetBoxHeight = (int) csParticleDataGetBoxHeight;
	Api.p_csParticleDataGetBoxDepth = (int) csParticleDataGetBoxDepth;
	Api.p_csParticleDataGetDirectionX = (int) csParticleDataGetDirectionX;
	Api.p_csParticleDataGetDirectionY = (int) csParticleDataGetDirectionY;
	Api.p_csParticleDataGetDirectionZ = (int) csParticleDataGetDirectionZ;
	Api.p_csParticleDataGetMinRate = (int) csParticleDataGetMinRate;
	Api.p_csParticleDataGetMaxRate = (int) csParticleDataGetMaxRate;
	Api.p_csParticleDataGetMinColor = (int) csParticleDataGetMinColor;
	Api.p_csParticleDataGetMaxColor = (int) csParticleDataGetMaxColor;
	Api.p_csParticleDataGetMinLifeTime = (int) csParticleDataGetMinLifeTime;
	Api.p_csParticleDataGetMaxLifeTime = (int) csParticleDataGetMaxLifeTime;
	Api.p_csParticleDataGetMaxAngle = (int) csParticleDataGetMaxAngle;
	Api.p_csParticleDataGetWidth = (int) csParticleDataGetWidth;
	Api.p_csParticleDataGetHeight = (int) csParticleDataGetHeight;
	Api.p_csParticleDataAffectors = (int) csParticleDataAffectors;
	Api.p_csParticleDataGetAffectorType = (int) csParticleDataGetAffectorType;
	Api.p_csParticleDataGetAffectorColor = (int) csParticleDataGetAffectorColor;
	Api.p_csParticleDataGetAffectorTime = (int) csParticleDataGetAffectorTime;
	Api.p_csParticleDataGetAffectorGravityX = (int) csParticleDataGetAffectorGravityX;
	Api.p_csParticleDataGetAffectorGravityY = (int) csParticleDataGetAffectorGravityY;
	Api.p_csParticleDataGetAffectorGravityZ = (int) csParticleDataGetAffectorGravityZ;
	Api.p_csSceneBegin = (int) csSceneBegin;
	Api.p_csSceneEnd = (int) csSceneEnd;
	Api.p_csSceneRender = (int) csSceneRender;
	Api.p_csSceneAmbient = (int) csSceneAmbient;
	Api.p_csSceneFog = (int) csSceneFog;
	Api.p_csSceneSkybox = (int) csSceneSkybox;
	Api.p_csSceneTransformation = (int) csSceneTransformation;
	Api.p_csShaderRegister = (int) csShaderRegister;
	Api.p_csShaderRegisterFile = (int) csShaderRegisterFile;
	Api.p_csShaderAsmRegister = (int) csShaderAsmRegister;
	Api.p_csShaderAsmRegisterFile = (int) csShaderAsmRegisterFile;
	Api.p_csShaderPixelConstant = (int) csShaderPixelConstant;
	Api.p_csShaderVertexConstant = (int) csShaderVertexConstant;
	Api.p_csStringToInt = (int) csStringToInt;
	Api.p_csStringToFloat = (int) csStringToFloat;
	Api.p_csStringFromInt = (int) csStringFromInt;
	Api.p_csStringFromFloat = (int) csStringFromFloat;
	Api.p_csStringLeft = (int) csStringLeft;
	Api.p_csStringRight = (int) csStringRight;
	Api.p_csStringMid = (int) csStringMid;
	Api.p_csStringReplace = (int) csStringReplace;
	Api.p_csStringFind = (int) csStringFind;
	Api.p_csStringUpper = (int) csStringUpper;
	Api.p_csStringLower = (int) csStringLower;
	Api.p_csStringTrim = (int) csStringTrim;
	Api.p_csStringChar = (int) csStringChar;
	Api.p_csStringAscii = (int) csStringAscii;
	Api.p_csStringLen = (int) csStringLen;
	Api.p_csStringField = (int) csStringField;
	Api.p_csTerrainNode = (int) csTerrainNode;
	Api.p_csTerrainScaleTexture = (int) csTerrainScaleTexture;
	Api.p_csTextureCreate = (int) csTextureCreate;
	Api.p_csTextureTargetCreate = (int) csTextureTargetCreate;
	Api.p_csTextureLoad = (int) csTextureLoad;
	Api.p_csTextureFree = (int) csTextureFree;
	Api.p_csTextureFile = (int) csTextureFile;
	Api.p_csTextureWidth = (int) csTextureWidth;
	Api.p_csTextureHeight = (int) csTextureHeight;
	Api.p_csTextureLock = (int) csTextureLock;
	Api.p_csTextureUnlock = (int) csTextureUnlock;
	Api.p_csTextureColorKey = (int) csTextureColorKey;
	Api.p_csTextureNormalize = (int) csTextureNormalize;
	Api.p_csTextureHWPointer = (int) csTextureHWPointer;
	Api.p_csVectorCreate = (int) csVectorCreate;
	Api.p_csVectorFree = (int) csVectorFree;
	Api.p_csVectorAdd = (int) csVectorAdd;
	Api.p_csVectorAddScale = (int) csVectorAddScale;
	Api.p_csVectorBetween = (int) csVectorBetween;
	Api.p_csVectorCopy = (int) csVectorCopy;
	Api.p_csVectorCrossProduct = (int) csVectorCrossProduct;
	Api.p_csVectorDotProduct = (int) csVectorDotProduct;
	Api.p_csVectorEqual = (int) csVectorEqual;
	Api.p_csVectorDistance = (int) csVectorDistance;
	Api.p_csVectorDistanceSquared = (int) csVectorDistanceSquared;
	Api.p_csVectorDiv = (int) csVectorDiv;
	Api.p_csVectorInterpolate = (int) csVectorInterpolate;
	Api.p_csVectorInvert = (int) csVectorInvert;
	Api.p_csVectorLength = (int) csVectorLength;
	Api.p_csVectorLengthSquared = (int) csVectorLengthSquared;
	Api.p_csVectorMul = (int) csVectorMul;
	Api.p_csVectorNormalize = (int) csVectorNormalize;
	Api.p_csVectorScale = (int) csVectorScale;
	Api.p_csVectorSet = (int) csVectorSet;
	Api.p_csVectorSub = (int) csVectorSub;
	Api.p_csVectorX = (int) csVectorX;
	Api.p_csVectorY = (int) csVectorY;
	Api.p_csVectorZ = (int) csVectorZ;
	Api.p_csXMLRead = (int) csXMLRead;
	Api.p_csXMLWrite = (int) csXMLWrite;
	Api.p_csXMLClose = (int) csXMLClose;
	Api.p_csXMLReadNode = (int) csXMLReadNode;
	Api.p_csXMLNodeType = (int) csXMLNodeType;
	Api.p_csXMLNodeName = (int) csXMLNodeName;
	Api.p_csXMLNodeData = (int) csXMLNodeData;
	Api.p_csXMLAttributeCount = (int) csXMLAttributeCount;
	Api.p_csXMLAttributeName = (int) csXMLAttributeName;
	Api.p_csXMLAttributeValue = (int) csXMLAttributeValue;
	Api.p_csXMLWriteHeader = (int) csXMLWriteHeader;
	Api.p_csXMLWriteElement = (int) csXMLWriteElement;
	Api.p_csXMLWriteClosingTag = (int) csXMLWriteClosingTag;
	Api.p_csXMLWriteText = (int) csXMLWriteText;
	Api.p_csXMLWriteLineBreak = (int) csXMLWriteLineBreak;
	return (int)&Api;
}
