#ifndef _WRAPFLOATS_H_
#define _WRAPFLOATS_H_

#include "common.h"

csInt csSoundGetMasterVolume_FWRAP(float volume_);
csInt csChannelGetMinDistance_FWRAP(int channel_);
csInt csChannelGetMaxDistance_FWRAP(int channel_);
csInt csChannelGetPan_FWRAP(int channel_);
csInt csChannelX_FWRAP(int channel_);
csInt csChannelY_FWRAP(int channel_);
csInt csChannelZ_FWRAP(int channel_);
csInt csChannelGetVolume_FWRAP(int channel_);
csInt csBillboardWidth_FWRAP(int billboard_);
csInt csBillboardHeight_FWRAP(int billboard_);
csInt csEventA_FWRAP();
csInt csEventB_FWRAP();
csInt csEventC_FWRAP();
csInt csFileReadFloat_FWRAP(int file_);
csInt csJoyAxis_FWRAP(int id_, int axis_);
csInt csMaterialGetShininess_FWRAP(int mat_);
csInt csMaterialGetParam_FWRAP(int mat_);
csInt csMaterialDataGetShininess_FWRAP(int mat_);
csInt csMaterialDataGetParam_FWRAP(int mat_);
csInt csMathFloor_FWRAP(float val_);
csInt csMathCeil_FWRAP(float val_);
csInt csMathAbs_FWRAP(float val_);
csInt csMathSqr_FWRAP(float val_);
csInt csMathSin_FWRAP(float val_);
csInt csMathCos_FWRAP(float val_);
csInt csMathTan_FWRAP(float val_);
csInt csMathASin_FWRAP(float val_);
csInt csMathACos_FWRAP(float val_);
csInt csMathATan_FWRAP(float val_);
csInt csMathATan2_FWRAP(float x_, float y_);
csInt csMathExp_FWRAP(float val_);
csInt csMathLog_FWRAP(float val_);
csInt csMathLog10_FWRAP(float val_);
csInt csMatrixElement_FWRAP(int matrix_, int row_, int column_);
csInt csMeshWidth_FWRAP(int mesh_);
csInt csMeshHeight_FWRAP(int mesh_);
csInt csMeshDepth_FWRAP(int mesh_);
csInt csNodeX_FWRAP(int node_, int absolute_);
csInt csNodeY_FWRAP(int node_, int absolute_);
csInt csNodeZ_FWRAP(int node_, int absolute_);
csInt csNodePitch_FWRAP(int node_);
csInt csNodeYaw_FWRAP(int node_);
csInt csNodeRoll_FWRAP(int node_);
csInt csNodeScaleX_FWRAP(int node_);
csInt csNodeScaleY_FWRAP(int node_);
csInt csNodeScaleZ_FWRAP(int node_);
csInt csNodeWidth_FWRAP(int node_);
csInt csNodeHeight_FWRAP(int node_);
csInt csNodeDepth_FWRAP(int node_);
csInt csParticleDataGetBoxWidth_FWRAP(int part_);
csInt csParticleDataGetBoxHeight_FWRAP(int part_);
csInt csParticleDataGetBoxDepth_FWRAP(int part_);
csInt csParticleDataGetDirectionX_FWRAP(int part_);
csInt csParticleDataGetDirectionY_FWRAP(int part_);
csInt csParticleDataGetDirectionZ_FWRAP(int part_);
csInt csParticleDataGetWidth_FWRAP(int part_);
csInt csParticleDataGetHeight_FWRAP(int part_);
csInt csParticleDataGetAffectorGravityX_FWRAP(int part_, int index_);
csInt csParticleDataGetAffectorGravityY_FWRAP(int part_, int index_);
csInt csParticleDataGetAffectorGravityZ_FWRAP(int part_, int index_);
csInt csStringToFloat_FWRAP(const char* str_);
csInt csVectorDotProduct_FWRAP(int vector_, int other_vector_);
csInt csVectorDistance_FWRAP(int vector_, float x_, float y_, float z_);
csInt csVectorDistanceSquared_FWRAP(int vector_, float x_, float y_, float z_);
csInt csVectorLength_FWRAP(int vector_);
csInt csVectorLengthSquared_FWRAP(int vector_);
csInt csVectorX_FWRAP(int vector_);
csInt csVectorY_FWRAP(int vector_);
csInt csVectorZ_FWRAP(int vector_);

csInt csSoundGetMasterVolume_FPT(float volume_);
csInt csChannelGetMinDistance_FPT(int channel_);
csInt csChannelGetMaxDistance_FPT(int channel_);
csInt csChannelGetPan_FPT(int channel_);
csInt csChannelX_FPT(int channel_);
csInt csChannelY_FPT(int channel_);
csInt csChannelZ_FPT(int channel_);
csInt csChannelGetVolume_FPT(int channel_);
csInt csBillboardWidth_FPT(int billboard_);
csInt csBillboardHeight_FPT(int billboard_);
csInt csEventA_FPT();
csInt csEventB_FPT();
csInt csEventC_FPT();
csInt csFileReadFloat_FPT(int file_);
csInt csJoyAxis_FPT(int id_, int axis_);
csInt csMaterialGetShininess_FPT(int mat_);
csInt csMaterialGetParam_FPT(int mat_);
csInt csMaterialDataGetShininess_FPT(int mat_);
csInt csMaterialDataGetParam_FPT(int mat_);
csInt csMathFloor_FPT(float val_);
csInt csMathCeil_FPT(float val_);
csInt csMathAbs_FPT(float val_);
csInt csMathSqr_FPT(float val_);
csInt csMathSin_FPT(float val_);
csInt csMathCos_FPT(float val_);
csInt csMathTan_FPT(float val_);
csInt csMathASin_FPT(float val_);
csInt csMathACos_FPT(float val_);
csInt csMathATan_FPT(float val_);
csInt csMathATan2_FPT(float x_, float y_);
csInt csMathExp_FPT(float val_);
csInt csMathLog_FPT(float val_);
csInt csMathLog10_FPT(float val_);
csInt csMatrixElement_FPT(int matrix_, int row_, int column_);
csInt csMeshWidth_FPT(int mesh_);
csInt csMeshHeight_FPT(int mesh_);
csInt csMeshDepth_FPT(int mesh_);
csInt csNodeX_FPT(int node_, int absolute_);
csInt csNodeY_FPT(int node_, int absolute_);
csInt csNodeZ_FPT(int node_, int absolute_);
csInt csNodePitch_FPT(int node_);
csInt csNodeYaw_FPT(int node_);
csInt csNodeRoll_FPT(int node_);
csInt csNodeScaleX_FPT(int node_);
csInt csNodeScaleY_FPT(int node_);
csInt csNodeScaleZ_FPT(int node_);
csInt csNodeWidth_FPT(int node_);
csInt csNodeHeight_FPT(int node_);
csInt csNodeDepth_FPT(int node_);
csInt csParticleDataGetBoxWidth_FPT(int part_);
csInt csParticleDataGetBoxHeight_FPT(int part_);
csInt csParticleDataGetBoxDepth_FPT(int part_);
csInt csParticleDataGetDirectionX_FPT(int part_);
csInt csParticleDataGetDirectionY_FPT(int part_);
csInt csParticleDataGetDirectionZ_FPT(int part_);
csInt csParticleDataGetWidth_FPT(int part_);
csInt csParticleDataGetHeight_FPT(int part_);
csInt csParticleDataGetAffectorGravityX_FPT(int part_, int index_);
csInt csParticleDataGetAffectorGravityY_FPT(int part_, int index_);
csInt csParticleDataGetAffectorGravityZ_FPT(int part_, int index_);
csInt csStringToFloat_FPT(const char* str_);
csInt csVectorDotProduct_FPT(int vector_, int other_vector_);
csInt csVectorDistance_FPT(int vector_, float x_, float y_, float z_);
csInt csVectorDistanceSquared_FPT(int vector_, float x_, float y_, float z_);
csInt csVectorLength_FPT(int vector_);
csInt csVectorLengthSquared_FPT(int vector_);
csInt csVectorX_FPT(int vector_);
csInt csVectorY_FPT(int vector_);
csInt csVectorZ_FPT(int vector_);

#endif // _WRAPFLOATS_H_
